server:
  port: 8091

# 通过配置文件的方式，配置路由
spring:
  cloud:
    gateway:
      routes:
#        - id: after_route
#          uri: http://www.baidu.com
#          predicates:
#            - After=2021-09-17T15:00:00.129+08:00[Asia/Shanghai]
# 等同于 GatewayRoutes 配置文件中的信息
        - id: selfMake
          uri: http://localhost:8088/
          predicates:
            - Path=/freekaiGateWay/**
          filters:
            - StripPrefix=1
