server:
  port: 8088

spring:
  application:
    name: service-provider

eureka:
  instance:
    prefer-ip-address: true
    instance-id: service-provider2
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://freekai:freekaiQaq@localhost:${eureka.client.eureka-server-port}/eureka
    eureka-server-port: 8081
